const DATA_URL="agenda.json",OVERRIDES_URL="status-overrides.json";let allEvents=[],overrides={};
function dateOnly(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[–—-]/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim()}
function locationFor(e){const c=e.campaign||{},mode=String(c.affichage_lieu||"3"),a=String(c.lieu||"").trim(),b=String(e.location||"").trim();if(mode==="0")return "";if(mode==="1")return a;if(mode==="2")return b;if(!a)return b;if(!b)return a;const x=norm(a),y=norm(b);return x===y||x.includes(y)||y.includes(x)?(a.length>=b.length?a:b):a+" – "+b}
function hour(d){const h=d.getHours(),m=d.getMinutes();return m? h+"h"+String(m).padStart(2,"0"):h+"h"}
function status(e){return String(overrides[e.uid]?.statut??e.campaign?.statut??"").trim()}
function monthLabel(y,m){return new Date(y,m,1).toLocaleDateString("fr-FR",{month:"long",year:"numeric"})}
function render(e){const c=e.campaign||{},s=new Date(e.start),end=e.end?new Date(e.end):null,l=locationFor(e),im=c.image?'<div class="thumb"><img src="'+esc(c.image)+'" alt=""></div>':'<div class="thumb emptyThumb">🎲</div>',logo=c.logo?'<div class="eventLogo"><img src="'+esc(c.logo)+'" alt=""></div>':"";const el=document.createElement("article");el.className="eventCard";el.innerHTML='<div class="date"><div class="weekday">'+esc(s.toLocaleDateString("fr-FR",{weekday:"short"}).toUpperCase())+'</div><div class="day">'+s.getDate()+'</div></div>'+im+'<div class="infoBlock"><div class="textCol"><div class="title">'+esc(c.titre||e.title||"Événement")+'</div>'+(c.sous_titre?'<div class="subtitle">'+esc(c.sous_titre)+'</div>':"")+'<div class="meta"><span>🕐 '+hour(s)+(end?" – "+hour(end):"")+'</span>'+(l?'<span>📍 '+esc(l)+'</span>':"")+'</div>'+(c.tarif?'<div class="info">💶 '+esc(c.tarif)+'</div>':"")+(c.inscription?'<div class="info">💬 '+esc(c.inscription)+'</div>':"")+(status(e)?'<div class="status">'+esc(status(e))+'</div>':"")+'</div>'+logo+'</div>';return el}
async function load(){try{const r=await fetch(DATA_URL+"?t="+Date.now()),j=await r.json();allEvents=j.events||[];try{const o=await fetch(OVERRIDES_URL+"?t="+Date.now());overrides=o.ok?await o.json():{}}catch(_){overrides={}}const offset=Number(document.body.dataset.monthOffset||0),now=new Date(),target=new Date(now.getFullYear(),now.getMonth()+offset,1),y=target.getFullYear(),m=target.getMonth();document.getElementById("pageDate").textContent=monthLabel(y,m);const today=dateOnly(now);const events=allEvents.filter(e=>{if(!e.start)return false;const d=new Date(e.start);if(d.getFullYear()!==y||d.getMonth()!==m)return false;return offset===0?d.getTime()>=today.getTime():true}).filter(e=>e.end?new Date(e.end).getTime()>Date.now():new Date(e.start).getTime()>=Date.now()).sort((a,b)=>new Date(a.start)-new Date(b.start));const grid=document.getElementById("eventGrid");grid.innerHTML="";if(!events.length){document.body.classList.add("empty");return}document.body.classList.remove("empty");events.forEach(e=>grid.appendChild(render(e)))}catch(err){console.error(err);document.body.classList.add("empty");document.getElementById("noEvent").textContent="Impossible de charger les événements.";}}
load();setInterval(load,60000);