const DATA_URL="agenda.json",OVERRIDES_URL="status-overrides.json";
const PAGE_SIZE=4, AUTO_PAGE_MS=10000;
let allEvents=[],overrides={},currentPage=0,totalPages=1,autoTimer=null;
function dateOnly(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[–—-]/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim()}
function locationFor(e){const c=e.campaign||{},mode=String(c.affichage_lieu||"3"),a=String(c.lieu||"").trim(),b=String(e.location||"").trim();if(mode==="0")return "";if(mode==="1")return a;if(mode==="2")return b;if(mode==="4")return a||b;if(!a)return b;if(!b)return a;const x=norm(a),y=norm(b);return x===y||x.includes(y)||y.includes(x)?(a.length>=b.length?a:b):a+" – "+b}
function hour(d){const h=d.getHours(),m=d.getMinutes();return m?h+"h"+String(m).padStart(2,"0"):h+"h"}
function status(e){return String(overrides[e.uid]?.statut??e.campaign?.statut??"").trim()}
function monthLabel(y,m){return new Date(y,m,1).toLocaleDateString("fr-FR",{month:"long",year:"numeric"})}
function render(e){const c=e.campaign||{},s=new Date(e.start),end=e.end?new Date(e.end):null,l=locationFor(e),im=c.image?'<div class="thumb"><img src="'+esc(c.image)+'" alt=""></div>':'<div class="thumb emptyThumb">🎲</div>',logo=c.logo?'<div class="eventLogo"><img src="'+esc(c.logo)+'" alt=""></div>':"",time=hour(s)+(end?" – "+hour(end):"");const el=document.createElement("article");el.className="eventCard";el.innerHTML='<div class="date"><div class="weekday">'+esc(s.toLocaleDateString("fr-FR",{weekday:"short"}).toUpperCase())+'</div><div class="day">'+s.getDate()+'</div><div class="time">'+esc(time)+'</div></div>'+im+'<div class="infoBlock"><div class="textCol"><div class="title">'+esc(c.titre||e.title||"Événement")+'</div>'+(c.sous_titre?'<div class="subtitle">'+esc(c.sous_titre)+"</div>":"")+(l?'<div class="meta"><span>📍 '+esc(l)+"</span></div>":"")+(c.tarif?'<div class="info">💶 '+esc(c.tarif)+"</div>":"")+(c.inscription?'<div class="info">💬 '+esc(c.inscription)+"</div>":"")+(status(e)?'<div class="status">'+esc(status(e))+"</div>":"")+"</div>"+logo+"</div>";return el}
function updatePager(){const pager=document.getElementById("pager");if(!pager)return;pager.classList.toggle("hidden",totalPages<=1);document.getElementById("pagePrev").disabled=currentPage<=0;document.getElementById("pageNext").disabled=currentPage>=totalPages-1;document.getElementById("pageNumber").textContent=totalPages>1?(currentPage+1)+" / "+totalPages:"";}
function showPage(page){if(!allEvents.length)return;currentPage=Math.max(0,Math.min(page,totalPages-1));const grid=document.getElementById("eventGrid");grid.innerHTML="";allEvents.slice(currentPage*PAGE_SIZE,currentPage*PAGE_SIZE+PAGE_SIZE).forEach(e=>grid.appendChild(render(e)));updatePager();resetAutoPage();}
function resetAutoPage(){clearInterval(autoTimer);if(totalPages>1)autoTimer=setInterval(()=>showPage(currentPage+1>=totalPages?0:currentPage+1),AUTO_PAGE_MS)}
function setupPager(){document.getElementById("pagePrev")?.addEventListener("click",()=>showPage(currentPage-1));document.getElementById("pageNext")?.addEventListener("click",()=>showPage(currentPage+1));}
async function load(){try{const r=await fetch(DATA_URL+"?t="+Date.now()),j=await r.json();allEvents=j.events||[];try{const o=await fetch(OVERRIDES_URL+"?t="+Date.now());overrides=o.ok?await o.json():{}}catch(_){overrides={}}const offset=Number(document.body.dataset.monthOffset||0),now=new Date(),target=new Date(now.getFullYear(),now.getMonth()+offset,1),y=target.getFullYear(),m=target.getMonth();document.getElementById("pageDate").textContent=monthLabel(y,m);const today=dateOnly(now);allEvents=allEvents.filter(e=>{if(!e.start)return false;const d=new Date(e.start);if(d.getFullYear()!==y||d.getMonth()!==m)return false;return offset===0?d.getTime()>=today.getTime():true}).filter(e=>e.end?new Date(e.end).getTime()>Date.now():new Date(e.start).getTime()>=Date.now()).sort((a,b)=>new Date(a.start)-new Date(b.start));totalPages=Math.max(1,Math.ceil(allEvents.length/PAGE_SIZE));currentPage=Math.min(currentPage,totalPages-1);const grid=document.getElementById("eventGrid");if(!allEvents.length){clearInterval(autoTimer);grid.innerHTML="";document.body.classList.add("empty");updatePager();return}document.body.classList.remove("empty");showPage(currentPage)}catch(err){console.error(err);document.body.classList.add("empty");document.getElementById("noEvent").textContent="Impossible de charger les événements.";clearInterval(autoTimer)}}
document.addEventListener("DOMContentLoaded",()=>{setupPager();load();setInterval(load,60000)});